# -*- coding: utf-8 -*-
"""Feature_engineering.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AK0xPeMokLUnw_2_8p-d3s8LcotCLt4v

#Feature Engineering
"""

import pandas as pd

"""Chargement des donnees traitees"""

dossier_donnees = "./Data/"
chemin_train = dossier_donnees + "train_pretraite.csv"
chemin_test = dossier_donnees + "test_pretraite.csv"

train = pd.read_csv(chemin_train)
test = pd.read_csv(chemin_test)

"""Création de nouvelles caractéristiques"""

# Ici, nous ajoutons des caractéristiques basées sur les données existantes.

# Ratio entre le solde et le revenu total
if 'Balance' in train.columns and 'EstimatedSalary' in train.columns:
    train['Ratio_Solde_Revenu'] = train['Balance'] / (train['EstimatedSalary'] + 1)
    test['Ratio_Solde_Revenu'] = test['Balance'] / (test['EstimatedSalary'] + 1)

# Total des produits possédés
if 'NumOfProducts' in train.columns:
    train['Total_Produits'] = train['NumOfProducts'] * train['IsActiveMember']
    test['Total_Produits'] = test['NumOfProducts'] * test['IsActiveMember']

"""Suppression des colonnes inutiles"""

# Ici, nous supprimons les colonnes non pertinentes ou redondantes.
colonnes_a_supprimer = ['RowNumber', 'CustomerId', 'Surname']
train.drop(columns=[col for col in colonnes_a_supprimer if col in train.columns], inplace=True)
test.drop(columns=[col for col in colonnes_a_supprimer if col in test.columns], inplace=True)

"""Sauvegarde des donnees apres Feature Engineering"""

train.to_csv(dossier_donnees + "train_feature_engineering.csv", index=False)
test.to_csv(dossier_donnees + "test_feature_engineering.csv", index=False)